name: flutter_package
description: Este é um exemplo usando a api do pub.dev onde o objectivo é listar os pacotes
author: Edvaldo Martins <edvaldonuniomartins@gmail.com>
homepage: https://github.com/EdvaldoMartins/flutter_package_pub_dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #ui
  cupertino_icons: ^0.1.3
  flutter_markdown: ^0.5.2
  flutter_svg: ^0.19.0
  html: ^0.14.0+2
  pull_to_refresh: 1.6.3
  customized:
    git:
      url: https://github.com/EdvaldoMartins/customized

  #state
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1

  #data class
  equatable: ^1.0.1
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1

  #network
  connectivity: ^0.4.8+6
  dio: ^3.0.10
  data_connection_checker: ^0.3.4
  http: ^0.12.1

  # Dependency Injection
  get_it: ^5.0.3
  injectable: ^1.0.5

  #utils
  fluttertoast: ^7.1.5
  share: ^0.6.3+5
  url_launcher: ^5.4.2
  dartz: ^0.9.1
  intl: ^0.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.9
  freezed: ^0.12.3
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.1
  build_resolvers: ^1.4.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Font
    - fonts:
        - asset: fonts/light.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/icons/
    - assets/images/


#    flutter packages pub run build_runner build --delete-conflicting-outputs
